export const BASE = "https://hiperdex.tv";
export const MANGA = "manga";
export const CF_RESOLVE = `${BASE}/`;
export const AUTH_HEADER = "x-cfg-auth";
/** Bundled default — also recovered from `/assets/index-*.js` on 401. */
export const DEFAULT_AUTH = "yceqt7qgu004";
export const PAGE_LIMIT = 30;
export const IMAGE_ACCEPT =
  "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8";

export const SORTS = [
  { id: "popular", title: "Popularity" },
  { id: "recent", title: "Latest" },
  { id: "relevance", title: "Relevance" },
  { id: "score", title: "Score" },
  { id: "newest", title: "Newest" },
  { id: "oldest", title: "Oldest" },
  { id: "alphabetical", title: "A-Z" },
] as const;

export const TYPES = [
  { id: "manga", title: "Manga" },
  { id: "manhwa", title: "Manhwa" },
  { id: "manhua", title: "Manhua" },
  { id: "novel", title: "Novel" },
  { id: "webtoon", title: "Webtoon" },
  { id: "one_shot", title: "One Shot" },
] as const;

export const STATUSES = [
  { id: "ongoing", title: "Ongoing" },
  { id: "completed", title: "Completed" },
  { id: "hiatus", title: "Hiatus" },
  { id: "cancelled", title: "Canceled" },
] as const;

export const RATINGS = [
  { id: "pornographic", title: "Pornographic" },
  { id: "erotica", title: "Erotica" },
  { id: "suggestive", title: "Suggestive" },
  { id: "safe", title: "Safe" },
] as const;

export const DEFAULT_MAX_RATING = "pornographic";

export const SETTINGS = {
  maxRating: "hiperdex.maxRating",
  cleanTitle: "hiperdex.cleanTitle",
  cleanRegex: "hiperdex.cleanRegex",
  noCleanBrowse: "hiperdex.noCleanBrowse",
} as const;

/** Keiyoushi Hiperdex genre list for search checkboxes. */
export const GENRES = [
  "4-Koma",
  "Action",
  "Adaptation",
  "Adult",
  "Adventure",
  "Age Gap",
  "Aliens",
  "Ancient Korea",
  "Anthology",
  "Campus",
  "Childhood Friends",
  "Comedy",
  "Cooking",
  "Crime",
  "Crossdressing",
  "Dance",
  "Delinquents",
  "Demons",
  "Doujinshi",
  "Drama",
  "Ecchi",
  "Escolar",
  "Fantasy",
  "Fellatio/Blowjob",
  "Fetish",
  "Full Color",
  "Furry",
  "Gender Bender",
  "Genderswap",
  "Ghosts",
  "Girls' Love",
  "Gore",
  "Guideverse",
  "Gyaru",
  "Hair Color Change",
  "Harem",
  "Hentai",
  "Heroes",
  "Historical",
  "Horror",
  "Human-Nonhuman Relationship",
  "Isekai",
  "Josei",
  "Korea",
  "Korean Ambience",
  "Korean BL",
  "Long Strip",
  "Long-Haired Male Character/s",
  "Long-Haired Male Lead",
  "Love Triangle/s",
  "Low Fantasy",
  "Maduro",
  "Mafia",
  "Magic",
  "Male Protagonist",
  "Manga",
  "Martial Arts",
  "Masculine Uke",
  "Mature",
  "Mecha",
  "Medical",
  "Military",
  "Monster Girls",
  "Monsters",
  "Monsters Invade Earth",
  "Murim",
  "Muscular Male Lead",
  "Muscular Uke",
  "Music",
  "Mystery",
  "Nameverse",
  "Ninja",
  "Office Workers",
  "Older Uke Younger Seme",
  "Oneshot",
  "Orphan Female Lead",
  "Police",
  "Post-Apocalyptic",
  "Psychological",
  "Red-Haired Male Lead",
  "Red-Haired Seme",
  "Regression",
  "Reincarnation",
  "Revenge",
  "Romance",
  "Samurai",
  "School Life",
  "Sci-fi",
  "Secret Relationship",
  "Seinen",
  "Sexual Violence",
  "Shota",
  "Shoujo",
  "Shoujo Ai",
  "Shounen",
  "Size Difference",
  "Slice of Life",
  "Smut",
  "Sobrenatural",
  "Sports",
  "Superhero",
  "Supernatural",
  "Survival",
  "Suspense",
  "Thriller",
  "Time Travel",
  "Tower",
  "Tragedy",
  "Uncensored",
  "Video Games",
  "Villainess",
  "Violence",
  "Virtual Reality",
  "Web Comic",
  "Webtoon",
  "Wuxia",
  "Yaoi",
  "Yuri",
] as const;
