export type TagOption = { id: string; title: string };

export const CATEGORIES: TagOption[] = [
  { id: "34", title: 'Adult' },
  { id: "7", title: 'Anal' },
  { id: "20", title: 'Big Breasts' },
  { id: "43", title: 'Comedy' },
  { id: "46", title: 'Compilation' },
  { id: "42", title: 'Doujinshi' },
  { id: "40", title: 'Ecchi' },
  { id: "14", title: 'Futanari' },
  { id: "26", title: 'Gender Bender' },
  { id: "31", title: 'Harem' },
  { id: "15", title: 'Incest' },
  { id: "16", title: 'Lactation' },
  { id: "50", title: 'Licensed' },
  { id: "17", title: 'Lolicon' },
  { id: "18", title: 'Masturbation' },
  { id: "33", title: 'Oneshot' },
  { id: "23", title: 'Rape' },
  { id: "30", title: 'Robotics' },
  { id: "41", title: 'Romance' },
  { id: "48", title: 'School Life' },
  { id: "32", title: 'Serialized' },
  { id: "44", title: 'Shotacon' },
  { id: "24", title: 'Tentacles' },
  { id: "49", title: 'Tragedy' },
  { id: "47", title: 'Un-censored' },
  { id: "27", title: 'Yaoi' },
  { id: "28", title: 'Yuri' },
];

export const TAGS: TagOption[] = [
  { id: "529", title: 'Abortion' },
  { id: "1423", title: 'Absent Parents' },
  { id: "878", title: 'Abusive Lover' },
  { id: "1587", title: 'Abusive' },
  { id: "416", title: 'Adapted to H-Anime' },
  { id: "1438", title: 'Addiction' },
  { id: "1634", title: 'Adopted Sister' },
  { id: "522", title: 'Adoption' },
  { id: "1451", title: 'Adoptive Siblings' },
  { id: "661", title: 'Adultery' },
  { id: "1459", title: 'Affair' },
  { id: "1599", title: 'Aggressive Lover' },
  { id: "1702", title: 'Ahegao' },
  { id: "1807", title: 'Airheads' },
  { id: "347", title: 'All-Girls School' },
  { id: "666", title: 'Alternative Ending' },
  { id: "1365", title: 'Anal Play' },
  { id: "2298", title: 'Analingus (Rimjob)' },
  { id: "1093", title: 'Angels' },
  { id: "1904", title: 'Animal Girls' },
  { id: "710", title: 'Animal Transformation' },
  { id: "589", title: 'Anthology' },
  { id: "913", title: 'Anthropomorphism' },
  { id: "975", title: 'Apron' },
  { id: "2360", title: 'Armpit Licking' },
  { id: "1843", title: 'Armpit Sex' },
  { id: "846", title: 'Arranged Marriage' },
  { id: "1719", title: 'Artificial Intelligence' },
  { id: "2190", title: 'Assjob' },
  { id: "327", title: 'Aunt-Nephew Relationship' },
  { id: "1661", title: 'Aunts' },
  { id: "1821", title: 'Authority Figures' },
  { id: "1867", title: 'BBW' },
  { id: "831", title: 'BDSM' },
  { id: "1263", title: 'BSDM' },
  { id: "2188", title: 'Bad Grammar' },
  { id: "350", title: 'Bathroom Intercourse' },
  { id: "403", title: 'Beach' },
  { id: "1227", title: 'Best Friends' },
  { id: "372", title: 'Bestiality' },
  { id: "610", title: 'Betrayal' },
  { id: "1591", title: 'Big Ass' },
  { id: "1514", title: 'Bikini' },
  { id: "645", title: 'Bishoujo' },
  { id: "1439", title: 'Bittersweet Ending' },
  { id: "391", title: 'Blackmail' },
  { id: "1875", title: 'Blind Characters' },
  { id: "1177", title: 'Blindfold' },
  { id: "1444", title: 'Bloomers' },
  { id: "952", title: 'Blow job' },
  { id: "2542", title: 'Blowjob Face' },
  { id: "1760", title: 'Body Modification' },
  { id: "444", title: 'Body Swap' },
  { id: "2183", title: 'Body Writing' },
  { id: "2772", title: 'Bodysuit' },
  { id: "317", title: 'Bondage' },
  { id: "395", title: 'Borderline H' },
  { id: "1321", title: 'Brainwash' },
  { id: "2191", title: 'Breast Expansion' },
  { id: "1351", title: 'Brides' },
  { id: "574", title: 'Brother Complex' },
  { id: "1305", title: 'Brother and Sister' },
  { id: "1782", title: 'Brother-in-law' },
  { id: "551", title: 'Bukkake' },
  { id: "600", title: 'Bullying' },
  { id: "1226", title: 'Bunny Girls' },
  { id: "1512", title: 'CGs' },
  { id: "2730", title: 'Cannibalism' },
  { id: "1633", title: 'Cat Ears' },
  { id: "957", title: 'Cat Girls' },
  { id: "339", title: 'Caught in the Act' },
  { id: "1196", title: 'Censored' },
  { id: "2184", title: 'Cervix Penetration' },
  { id: "549", title: 'Character Who Bullies the One They Love' },
  { id: "351", title: 'Cheating' },
  { id: "1339", title: 'Cheerleaders' },
  { id: "2773", title: 'Chikan' },
  { id: "1852", title: 'Child Abuse' },
  { id: "575", title: 'Child Born From Incest' },
  { id: "1663", title: 'Child Prostitute' },
  { id: "309", title: 'Childhood Friends' },
  { id: "310", title: 'Childhood Love' },
  { id: "2344", title: 'Chinese Dress' },
  { id: "1819", title: 'Chubby' },
  { id: "1586", title: 'Club President' },
  { id: "1808", title: 'Clumsy Character' },
  { id: "1739", title: 'Co-workers' },
  { id: "415", title: 'Collection of Inter-Linked Stories' },
  { id: "352", title: 'Collection of Short Stories/Oneshots' },
  { id: "834", title: 'Confession' },
  { id: "755", title: 'Corruption' },
  { id: "379", title: 'Cosplay' },
  { id: "1340", title: 'Cousins' },
  { id: "1371", title: 'Cow Girls' },
  { id: "1037", title: 'Creampie' },
  { id: "343", title: 'Crossdressing' },
  { id: "1754", title: 'Cunnilingus' },
  { id: "1277", title: 'Dark Skin' },
  { id: "1364", title: 'Debt-Motivated Prostitution' },
  { id: "1154", title: 'Debts' },
  { id: "516", title: 'Deception' },
  { id: "1436", title: 'Deep Throat' },
  { id: "1246", title: 'Defloration' },
  { id: "680", title: 'Delinquents' },
  { id: "1453", title: 'Demon Girls' },
  { id: "1666", title: 'Demon Hunters' },
  { id: "1152", title: 'Demons' },
  { id: "900", title: 'Doctor-Patient Relationship' },
  { id: "353", title: 'Dog Girls' },
  { id: "427", title: 'Double Penetration' },
  { id: "446", title: 'Drugs' },
  { id: "438", title: 'Drunk Intercourse' },
  { id: "864", title: 'Drunk' },
  { id: "1370", title: 'Elf-Elves' },
  { id: "2312", title: 'Emotionless Sex' },
  { id: "1740", title: 'Enema Play' },
  { id: "803", title: 'Enemies Become Lovers' },
  { id: "302", title: 'Ero-Guro' },
  { id: "404", title: 'Exhibitionism' },
  { id: "1831", title: 'Facesitting' },
  { id: "1368", title: 'Fairy-Fairies' },
  { id: "1616", title: 'Family Love' },
  { id: "1623", title: 'Family Secrets' },
  { id: "1021", title: 'Father and Daughter' },
  { id: "1922", title: 'Father-in-Law' },
  { id: "320", title: 'Female Dominance' },
  { id: "1030", title: 'Fetish' },
  { id: "1745", title: 'Fight Between Lovers' },
  { id: "1389", title: 'Fingering' },
  { id: "670", title: 'First Love' },
  { id: "428", title: 'Fisting' },
  { id: "2505", title: 'Foot Licking' },
  { id: "1058", title: 'Foot job' },
  { id: "1617", title: 'Forced Marriage' },
  { id: "1320", title: 'Forced Sex' },
  { id: "1746", title: 'Forced into a Relationship' },
  { id: "330", title: 'Foursome' },
  { id: "1268", title: 'Fox Girls' },
  { id: "1769", title: 'Friends Become Lovers' },
  { id: "468", title: 'Full Color' },
  { id: "2315", title: 'Furry' },
  { id: "2309", title: 'Futa on Female' },
  { id: "1850", title: 'Futa on Male' },
  { id: "429", title: 'Gang Rape' },
  { id: "462", title: 'Gangbang' },
  { id: "696", title: 'Ganguro' },
  { id: "2743", title: 'Ghost' },
  { id: "2278", title: 'Giantess' },
  { id: "1960", title: 'Girls Only' },
  { id: "465", title: 'Glasses' },
  { id: "720", title: 'God-Human Relationship' },
  { id: "1309", title: 'Goddess' },
  { id: "311", title: 'Group Intercourse' },
  { id: "2185", title: 'Gyaru' },
  { id: "2359", title: 'Hairy Armpit' },
  { id: "534", title: 'Hand Job' },
  { id: "491", title: 'Happy Sex' },
  { id: "1397", title: 'Hardcore' },
  { id: "1487", title: 'Harem-seeking Male Lead' },
  { id: "1744", title: 'Hot Springs' },
  { id: "555", title: 'Housewife-Housewives' },
  { id: "1853", title: 'Human Pet' },
  { id: "1724", title: 'Human Toilets' },
  { id: "459", title: 'Human-Nonhuman Relationship' },
  { id: "552", title: 'Humiliation' },
  { id: "1732", title: 'Hypnotism' },
  { id: "1211", title: 'Idols' },
  { id: "1358", title: 'Impregnation' },
  { id: "2506", title: 'Inari' },
  { id: "753", title: 'Incest as a Subplot' },
  { id: "423", title: 'Infidelity' },
  { id: "2186", title: 'Inflation' },
  { id: "2763", title: 'Insect' },
  { id: "431", title: 'Inverted Nipples' },
  { id: "2650", title: 'Isekai (Otherworld)' },
  { id: "441", title: 'Jealous Lover' },
  { id: "331", title: 'Jealousy' },
  { id: "408", title: 'Kidnapping' },
  { id: "1283", title: 'Kimono' },
  { id: "2507", title: 'Konkon' },
  { id: "2158", title: 'Korean Comic' },
  { id: "1759", title: 'Kunoichi (Ninja Girls)' },
  { id: "990", title: 'Large Dicks' },
  { id: "2187", title: 'Leotard' },
  { id: "332", title: 'Lingerie' },
  { id: "1580", title: 'Little Sisters' },
  { id: "1771", title: 'Live-in Lover' },
  { id: "2753", title: 'Lizard Girl' },
  { id: "1326", title: 'Love At First Sight' },
  { id: "1490", title: 'Love Rivals' },
  { id: "1167", title: 'Love Triangles' },
  { id: "354", title: 'MILFs' },
  { id: "539", title: 'Magic' },
  { id: "565", title: 'Magical Girls' },
  { id: "912", title: 'Maids' },
  { id: "681", title: 'Male Dominance' },
  { id: "659", title: 'Mangaka' },
  { id: "662", title: 'Masochists' },
  { id: "880", title: 'Master-Pet Relationship' },
  { id: "460", title: 'Master-Servant Relationship' },
  { id: "389", title: 'Master-Slave Relationship' },
  { id: "1714", title: 'Mermaids' },
  { id: "303", title: 'Mind Break' },
  { id: "304", title: 'Mind Control' },
  { id: "1114", title: 'Molesters' },
  { id: "1409", title: 'Monster Girls' },
  { id: "1243", title: 'Monster Sex' },
  { id: "1175", title: 'Monsters' },
  { id: "2769", title: 'Moral Degeneration' },
  { id: "342", title: 'Mother Complex' },
  { id: "784", title: 'Mother and Daughter' },
  { id: "393", title: 'Mother and Son' },
  { id: "1716", title: 'Mother-in-Law' },
  { id: "1826", title: 'Multiple Penetration' },
  { id: "2714", title: 'Necrophilia' },
  { id: "1741", title: 'Neighbors' },
  { id: "370", title: 'Netorare' },
  { id: "2243", title: 'Netori' },
  { id: "451", title: 'Newlyweds' },
  { id: "1717", title: 'Nipple Intercourse' },
  { id: "944", title: 'Nipple Play' },
  { id: "2503", title: 'No Penetration' },
  { id: "461", title: 'Non-Human Pregnancy' },
  { id: "1185", title: 'Nuns' },
  { id: "1046", title: 'Nurses' },
  { id: "605", title: 'Obsessive Love' },
  { id: "1738", title: 'Office Ladies' },
  { id: "2762", title: 'Old Lady' },
  { id: "2331", title: 'Old Man' },
  { id: "1366", title: 'Older Brother' },
  { id: "1648", title: 'Older Female Young Boy' },
  { id: "355", title: 'Older Female Younger Male' },
  { id: "1229", title: 'Older Male Younger Female' },
  { id: "1241", title: 'Older Sister' },
  { id: "504", title: 'Outdoor Intercourse' },
  { id: "360", title: 'Paizuri' },
  { id: "1275", title: 'Pantyhose' },
  { id: "2303", title: 'Partial Censorship' },
  { id: "665", title: 'Partially Colored' },
  { id: "1736", title: 'Pegging' },
  { id: "576", title: 'Personality Change' },
  { id: "387", title: 'Perverted Boss' },
  { id: "300", title: 'Perverted Characters' },
  { id: "366", title: 'Perverted Teachers' },
  { id: "1526", title: 'Perverts' },
  { id: "2771", title: 'Petplay' },
  { id: "1328", title: 'Pets' },
  { id: "1465", title: 'Piercings' },
  { id: "1657", title: 'Plain Girls' },
  { id: "688", title: 'Plastic Surgery' },
  { id: "312", title: 'Polygamy' },
  { id: "1317", title: 'Poor Characters' },
  { id: "2282", title: 'Poor Grammar' },
  { id: "1440", title: 'Porn Industry' },
  { id: "367", title: 'Porn Stars' },
  { id: "530", title: 'Porn with Plot' },
  { id: "1656", title: 'Possessed' },
  { id: "677", title: 'Possession' },
  { id: "1602", title: 'Possessive Lover' },
  { id: "305", title: 'Pregnancy' },
  { id: "1543", title: 'Pretend Rape' },
  { id: "1662", title: 'Priestesses' },
  { id: "1140", title: 'Priests' },
  { id: "1160", title: 'Princes' },
  { id: "1161", title: 'Princesses' },
  { id: "618", title: 'Prisoners' },
  { id: "1608", title: 'Proactive Protagonist' },
  { id: "1528", title: 'Producers' },
  { id: "394", title: 'Prostitution' },
  { id: "507", title: 'Public Intercourse' },
  { id: "406", title: 'Public Nudity' },
  { id: "787", title: 'Punishment Sex' },
  { id: "1418", title: 'Punishment' },
  { id: "1434", title: 'Queens' },
  { id: "470", title: 'Rabbit Girls' },
  { id: "567", title: 'Reverse Harem' },
  { id: "376", title: 'Reverse Rape' },
  { id: "2281", title: 'Rewrite' },
  { id: "726", title: 'Rich Boy' },
  { id: "727", title: 'Rich Family' },
  { id: "368", title: 'Rich Girl' },
  { id: "2774", title: 'Rough Grammar' },
  { id: "505", title: 'Rushed Ending/Axed' },
  { id: "663", title: 'Sadist' },
  { id: "499", title: 'Sadomasochism' },
  { id: "432", title: 'Scat' },
  { id: "995", title: 'School Girls' },
  { id: "313", title: 'School Intercourse' },
  { id: "478", title: 'School Nurse-Student Relationship' },
  { id: "1491", title: 'Secret Crush' },
  { id: "399", title: 'Secret Relationship' },
  { id: "1556", title: 'Seduction' },
  { id: "443", title: 'Senpai-Kouhai Relationship' },
  { id: "301", title: 'Sex Addicts' },
  { id: "400", title: 'Sex Friends Become Lovers' },
  { id: "629", title: 'Sex Friends' },
  { id: "450", title: 'Sex Industry' },
  { id: "1273", title: 'Sex Slaves' },
  { id: "837", title: 'Sex Toys' },
  { id: "695", title: 'Sexual Abuse' },
  { id: "476", title: 'Sexual Assault' },
  { id: "1611", title: 'Sexual Frustration' },
  { id: "2325", title: 'Shemale' },
  { id: "652", title: 'Shy Characters' },
  { id: "655", title: 'Sibling Love' },
  { id: "440", title: 'Sister Complex' },
  { id: "1403", title: 'Sister and Brother' },
  { id: "2684", title: 'Sister-in-Law' },
  { id: "1330", title: 'Sisters' },
  { id: "811", title: 'Sketchy Art Style' },
  { id: "2729", title: 'Skinsuit' },
  { id: "583", title: 'Sleep Intercourse' },
  { id: "1377", title: 'Sluts' },
  { id: "434", title: 'Small Breasts' },
  { id: "909", title: 'Son Complex' },
  { id: "1387", title: 'Spirits' },
  { id: "2768", title: 'Squirting' },
  { id: "1346", title: 'Star-Crossed Lover/s' },
  { id: "531", title: 'Step-Daughter' },
  { id: "532", title: 'Step-Father' },
  { id: "533", title: 'Step-Father/Step-Daughter Relationship' },
  { id: "770", title: 'Step-Mother' },
  { id: "334", title: 'Step-Mother/Step-Son Relationship' },
  { id: "371", title: 'Step-Sibling Love' },
  { id: "521", title: 'Step-Siblings' },
  { id: "833", title: 'Step-Son' },
  { id: "1327", title: 'Stockings' },
  { id: "641", title: 'Student Council' },
  { id: "315", title: 'Student-Tutor Relationship' },
  { id: "378", title: 'Succubus' },
  { id: "609", title: 'Sudden Appearance' },
  { id: "425", title: 'Sudden Confession' },
  { id: "1179", title: 'Swimsuit/s' },
  { id: "2694", title: 'Swinging' },
  { id: "1479", title: 'Tanned' },
  { id: "1126", title: 'Teacher-Student Relationship' },
  { id: "369", title: 'Teacher-Teacher Relationship' },
  { id: "1388", title: 'Teachers' },
  { id: "1686", title: 'Threesome (MFF)' },
  { id: "1688", title: 'Threesome (MMF)' },
  { id: "335", title: 'Threesome (Other)' },
  { id: "2300", title: 'Time Stop' },
  { id: "650", title: 'Tomboy' },
  { id: "2189", title: 'Torture' },
  { id: "518", title: 'Transgender' },
  { id: "344", title: 'Trap' },
  { id: "553", title: 'Tribadism' },
  { id: "653", title: 'Tsundere' },
  { id: "591", title: 'Tutors' },
  { id: "578", title: 'Twincest' },
  { id: "336", title: 'Twins' },
  { id: "1923", title: 'Uncle and Niece' },
  { id: "414", title: 'Unlucky Character/s' },
  { id: "1284", title: 'Unrequited Love' },
  { id: "2313", title: 'Unusual Pupils' },
  { id: "1157", title: 'Urethral Intercourse' },
  { id: "817", title: 'Urethral Play' },
  { id: "435", title: 'Urination' },
  { id: "1136", title: 'Vampires' },
  { id: "1137", title: 'Virgins' },
  { id: "588", title: 'Virtual Reality' },
  { id: "1841", title: 'Vore' },
  { id: "361", title: 'Voyeurism' },
  { id: "1334", title: 'Waitresses' },
  { id: "2597", title: 'Webtoon' },
  { id: "877", title: 'Werewolf' },
  { id: "544", title: 'Widow' },
  { id: "613", title: 'Wife Corruption' },
  { id: "545", title: 'Wife Depravity' },
  { id: "1385", title: 'Wife-Wives' },
  { id: "1485", title: 'Witches' },
  { id: "1412", title: 'Wolf Girls' },
  { id: "1071", title: 'X-Ray' },
  { id: "873", title: 'Yandere' },
  { id: "1029", title: 'Youkai' },
  { id: "500", title: 'Young Master' },
  { id: "2342", title: 'Yuri as a Subplot' },
  { id: "2672", title: 'Zombies' },
];
